# Generated by Django 4.2 on 2023-04-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('C', 'Circle'), ('O', 'Octagon'), ('H', 'Hollow')], default='C', max_length=1)),
                ('material', models.CharField(choices=[('G', 'Golden'), ('S', 'Silver'), ('B', 'Bronze')], default='G', max_length=1)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
            ],
        ),
    ]
