# Generated by Django 4.2 on 2023-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_formatmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.IntegerField(verbose_name='Year the coin was struck'),
        ),
    ]
