# Generated by Django 4.2 on 2023-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_imperfection'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='imperfections',
            field=models.ManyToManyField(to='main_app.imperfection'),
        ),
    ]
